//! Error/warning tables transliterated from vasm 1.7h general_errors.h,
//! syntax/mot/syntax_errors.h, cpus/m68k/cpu_errors.h, output_errors.h.
//! Numbering: general 1.., syntax 1001.., cpu 2001.., output 3001.. (error.h).

pub const ERROR: u32 = 1;
pub const WARNING: u32 = 2;
pub const FATAL: u32 = 16;
pub const MESSAGE: u32 = 32;
pub const DONTWARN: u32 = 64;
pub const NOLINE: u32 = 256;

pub const FIRST_GENERAL_ERROR: u32 = 1;
pub const FIRST_SYNTAX_ERROR: u32 = 1001;
pub const FIRST_CPU_ERROR: u32 = 2001;
pub const FIRST_OUTPUT_ERROR: u32 = 3001;

pub const GENERAL_ERRORS: &[(&str, u32)] = &[
    ("illegal operand types", ERROR),
    ("unknown mnemonic <%s>", ERROR),
    ("unknown section <%s>", ERROR),
    ("no current section specified", ERROR),
    ("internal error %d in line %d of %s", ERROR | FATAL),
    ("symbol <%s> redefined", WARNING),
    ("%c expected", WARNING),
    ("cannot resolve section <%s>, maximum number of passes reached", NOLINE | ERROR | FATAL),
    ("instruction not supported on selected architecture", ERROR),
    ("number or identifier expected", ERROR),
    ("could not initialize %s module", NOLINE | ERROR | FATAL),
    ("multiple input files", NOLINE | ERROR),
    ("could not open <%s> for input", NOLINE | ERROR | FATAL),
    ("could not open <%s> for output", NOLINE | ERROR | FATAL),
    ("unknown option <%s>", NOLINE | ERROR),
    ("no input file specified", NOLINE | ERROR | FATAL),
    ("could not initialize output module <%s>", NOLINE | ERROR | FATAL),
    ("out of memory", NOLINE | ERROR | FATAL),
    ("symbol <%s> recursively defined", ERROR | FATAL),
    ("fail: %s", ERROR),
    ("section offset is lower than current pc", ERROR | FATAL),
    ("target data type overflow (%d bits)", WARNING),
    ("undefined symbol <%s>", NOLINE | ERROR),
    ("trailing garbage after option -%c", NOLINE | WARNING),
    ("missing macro parameters", ERROR),
    ("missing end directive for macro \"%s\"", ERROR | FATAL),
    ("macro definition inside macro \"%s\"", ERROR | FATAL),
    ("maximum number of %d macro arguments exceeded", ERROR),
    ("option -%c was specified twice", NOLINE | WARNING),
    ("read error on <%s>", NOLINE | ERROR | FATAL),
    ("expression must be constant", ERROR),
    ("initialized data in bss", WARNING),
    ("missing end directive in repeat-block", ERROR | FATAL),
    ("#%d is not a valid warning message", NOLINE | ERROR),
    ("relocation not allowed", ERROR),
    ("illegal escape sequence \\%c", WARNING),
    ("no current macro to exit", ERROR),
    ("internal symbol %s redefined by user", FATAL),
    ("illegal relocation", ERROR),
    ("label name conflicts with mnemonic", WARNING),
    ("label name conflicts with directive", WARNING),
    ("division by zero", ERROR),
    ("illegal macro argument", ERROR),
    ("reloc org is already set", ERROR | FATAL),
    ("reloc org was not set", ERROR),
    ("illegal negative value", ERROR),
    ("bad file-offset argument", ERROR),
    ("assertion \"%s\" failed: %s", ERROR),
    ("cannot declare structure within structure", ERROR),
    ("no structure", ERROR),
    ("instruction has been auto-aligned", WARNING),
    ("macro name conflicts with mnemonic", WARNING),
    ("macro name conflicts with directive", WARNING),
    ("non-relocatable expression in equate <%s>", NOLINE | ERROR),
    ("initialized data in offset section", WARNING),
    ("illegal structure recursion", ERROR | FATAL),
    ("maximum number of macro recursions (%d) reached", ERROR | FATAL),
    ("data has been auto-aligned", WARNING),
    ("register symbol <%s> redefined", ERROR),
    ("cannot evaluate constant huge integer expression", ERROR),
    ("cannot evaluate floating point expression", ERROR),
    ("imported symbol <%s> was not referenced", WARNING),
    ("symbol <%s> already defined with %s scope", WARNING),
    ("unexpected \"else\" without \"if\"", ERROR),
    ("unexpected \"endif\" without \"if\"", ERROR),
    ("maximum if-nesting depth exceeded (%d levels)", FATAL | ERROR),
    ("\"endif\" missing for conditional block started at %s line %d", ERROR),
    ("repeatedly defined symbol <%s>", ERROR),
    ("macro <%s> does not exist", ERROR),
    ("register <%s> does not exist", ERROR),
    ("register symbol <%s> has wrong type", ERROR),
    ("cannot mix positional and keyword arguments", ERROR),
    ("undefined macro argument name", ERROR),
    ("required macro argument %d was left out", ERROR),
];

pub const SYNTAX_ERRORS: &[(&str, u32)] = &[
    ("mnemonic expected", ERROR),
    ("invalid extension", ERROR),
    ("no space before operands", WARNING),
    ("too many closing parentheses", WARNING),
    ("missing closing parentheses", WARNING),
    ("missing operand", ERROR),
    ("garbage at end of line", WARNING),
    ("syntax error", ERROR),
    ("invalid data operand", ERROR),
    (", expected", WARNING),
    ("identifier expected", ERROR),
    ("directive has no effect", WARNING),
    ("unexpected \"%s\" without \"%s\"", ERROR),
    ("illegal section type", ERROR),
    ("macro id insert on empty stack", ERROR),
    ("illegal memory type", ERROR),
    ("macro id stack overflow", ERROR),
    ("macro id pull without matching push", ERROR),
    ("check comment", WARNING),
    ("invalid numeric expansion", ERROR),
    ("einline without inline", ERROR),
    ("missing %c", WARNING),
    ("maximum inline nesting depth exceeded (%d)", ERROR),
];

pub const CPU_ERRORS: &[(&str, u32)] = &[
    ("instruction not supported on selected architecture", FATAL | ERROR),
    ("illegal addressing mode", ERROR),
    ("invalid register list", ERROR),
    ("missing ) in register indirect addressing mode", ERROR),
    ("address register required", ERROR),
    ("bad size extension", ERROR),
    ("displacement at bad position", WARNING),
    ("base or index register expected", ERROR),
    ("missing ] in memory indirect addressing mode", ERROR),
    ("no extension allowed here", WARNING),
    ("illegal scale factor", ERROR),
    ("can't scale PC register", WARNING),
    ("index register expected", ERROR),
    ("too many ] in memory indirect addressing mode", ERROR),
    ("missing outer displacement", ERROR),
    ("%c expected", ERROR),
    ("can't use PC register as index", ERROR),
    ("double registers in list", WARNING),
    ("data register required", ERROR),
    ("illegal bitfield width/offset", ERROR),
    ("constant integer expression required", ERROR),
    ("value from -64 to 63 required for k-factor", ERROR),
    ("need 32 bits to reference a program label", WARNING),
    ("option expected", ERROR),
    ("absolute value expected", ERROR),
    ("operand value out of range: %ld (valid: %ld..%ld)", ERROR),
    ("label in operand required", ERROR),
    ("%ld to fix", WARNING),
    ("branch destination out of range", ERROR),
    ("displacement out of range", ERROR),
    ("absolute displacement expected", ERROR),
    ("unknown option %c%c ignored", WARNING),
    ("absolute short address out of range", ERROR),
    ("deprecated instruction alias", WARNING),
    ("illegal opcode extension", FATAL | ERROR),
    ("extension for unsized instruction ignored", WARNING),
    ("immediate operand out of range", ERROR),
    ("immediate operand has illegal type or size", ERROR),
    ("data objects with %d bits size are not supported", ERROR),
    ("data out of range", ERROR),
    ("data has illegal type", ERROR),
    ("illegal combination of ColdFire addressing modes", ERROR),
    ("FP register required", ERROR),
    ("unknown cpu type", ERROR),
    ("register expected", ERROR),
    ("link.w changed to link.l", WARNING),
    ("branch out of range changed to jmp", WARNING),
    ("lea-displacement out of range, changed into move/add", WARNING),
    ("translated (A%d) into (0,A%d) for movep", WARNING),
    ("operand optimized: %s", MESSAGE),
    ("operand translated: %s", MESSAGE),
    ("instruction optimized: %s", MESSAGE),
    ("instruction translated: %s", MESSAGE),
    ("branch optimized into: b<cc>.%c", MESSAGE),
    ("branch translated into: b<cc>.%c", MESSAGE),
    ("basereg A%d already in use", ERROR),
    ("basereg A%d is already free", WARNING),
    ("short-branch to following instruction turned into a nop", WARNING),
    ("not a valid small data register", ERROR),
    ("small data mode is not enabled", ERROR),
    ("division by zero", WARNING),
];

pub const OUTPUT_ERRORS: &[(&str, u32)] = &[
    ("sections must not overlap", FATAL | ERROR | NOLINE),
    ("output module doesn't support cpu %s", ERROR | NOLINE),
    ("write error", FATAL | ERROR | NOLINE),
    ("section attributes <%s> not suppported", ERROR | NOLINE),
    ("reloc type %d, size %u, mask 0x%lx (symbol %s + 0x%lx) not supported", ERROR | NOLINE),
    ("reloc type %d not supported", ERROR | NOLINE),
    ("undefined symbol <%s>", ERROR | NOLINE),
    ("output module doesn't allow multiple sections of the same type (%s)", FATAL | ERROR | NOLINE),
    ("undefined symbol <%s> at %s+0x%lx, reloc type %d", ERROR | NOLINE),
    ("section <%s>: alignment padding (%lu) not a multiple of %lu at 0x%llx", WARNING | NOLINE),
    ("weak symbol <%s> not supported by output format, treating as global", WARNING | NOLINE),
    ("address 0x%llx out of range for selected format", ERROR | NOLINE),
    ("reloc type %d, mask 0x%lx to symbol %s + 0x%lx does not fit into %u bits", ERROR),
];
